version: "3.9"
services:
  app:
    build: .
    container_name: app-server
    ports:
      - "8000:8000"
  redis:
    image: redis:6.2.6-alpine
    restart: always
    container_name: redis-server
    ports:
      - 6379:6379