"""Add field in Document model

Revision ID: 7586473d9253
Revises: 2b6f41336e3b
Create Date: 2023-01-24 18:29:59.332136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7586473d9253'
down_revision = '2b6f41336e3b'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'document', ['doc_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='unique')
    op.drop_column('document', 'doc_id')
    # ### end Alembic commands ###
