"""FK relations

Revision ID: 2b6f41336e3b
Revises: eb4dc226d5a5
Create Date: 2023-01-21 12:55:26.499331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6f41336e3b'
down_revision = 'eb4dc226d5a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    # ### end Alembic commands ###
